version: '3.8'

services:
  django:
    container_name: django
    environment:
      IMAGE_TAG: ${IMAGE_TAG}
    build:
      context: ./rest
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 8000:8000
    depends_on:
      - geoserver
      - my-postgres
  geoserver:
    container_name: geoserver
    image: docker.osgeo.org/geoserver:2.25.1
    ports:
      - 8080:8080

  my-postgres:
    container_name: my-postgres
    image: postgres:15
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django2024
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
volumes:
  static_volume:

networks:
  default:
    external: true
    name: mynetwork