version: '3.8'

services:
  django:
    environment:
      IMAGE_TAG: ${IMAGE_TAG}
    image: "ghcr.io/romser1337/django-${IMAGE_TAG}:latest"
    build:
      context: ./rest
    command: gunicorn rest.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    depends_on:
      - geoserver
      - my-postgres
  geoserver:
    image: docker.osgeo.org/geoserver:2.25.1
    ports:
      - 8080:8080
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django2024
      - POSTGRES_DB=postgres

  my-postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django2024
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
volumes:
  static_volume:

#networks:
#  default:
#    external: true
#    name: mynetwork