version: '3.8'

services:
  web:
    image: ghcr.io/romser1337/django:latest
    build:
      context: ./rest
      dockerfile: Dockerfile
    command: gunicorn rest.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
volumes:
  static_volume:

#networks:
#  default:
#    external: true
#    name: mynetwork