version: '3.8'

services:
  web:
    build:
      context: ./rest
      dockerfile: Dockerfile
    command: gunicorn rest.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
  nginx:
    build:
      context: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web
volumes:
  static_volume:

networks:
  default:
    name: mynetwork