name: avantDjango

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.actor }}/docker-image-github:latest

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Django image
      run: docker build . --file rest/Dockerfile --tag "${{ github.actor }}"/django:latest --label "runnumber=${GITHUB_RUN_ID}"

    - name: Build the Nginx image
      run: docker build . --file nginx/Dockerfile --tag "${{ github.actor }}"/nginx:latest --label "runnumber=${GITHUB_RUN_ID}"

    - name: Log in to registry
      run: echo "${{ secrets.PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push image Nginx
      run: docker push "${{ env.REGISTRY }}"/"${{ github.actor }}"/nginx:latest

    - name: Push image Django
      run: docker push "${{ env.REGISTRY }}"/"${{ github.actor }}"/django:latest
