name: avantDjango

on:
  push:
    branches: [ "master", "feature/**" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.actor }}/docker-image-github:latest

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch

    - name: Character replacement
      shell: bash
      run: |
        branch=${{ steps.extract_branch.outputs.branch }}
        BRANCH_NAME="${branch////-}"
        echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT
      id: replace_branch

#    - name: Build the Docker image
#      env:
#        IMAGE_TAG: ${{ steps.replace_branch.outputs.branch }}
#      run: IMAGE_TAG=${{env.IMAGE_TAG }} docker-compose up -d

    - name: Build the Docker image
      run: docker build . --file rest/Dockerfile --tag "${{ env.REGISTRY }}"/"${{ github.actor }}"/django:latest
      run: docker build . --file rest/Dockerfile --tag "${{ env.REGISTRY }}"/"${{ github.actor }}"/django-"${{ steps.replace_branch.outputs.branch }}":latest

    - name: Log in to registry
      run: echo "${{ secrets.PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push image Django
      run: docker push "${{ env.REGISTRY }}"/"${{ github.actor }}"/django-"${{ steps.replace_branch.outputs.branch }}":latest
